# Generated by Django 3.2.16 on 2022-12-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='topic.topic')),
                ('topic2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic2', to='topic.topic')),
                ('topic3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic3', to='topic.topic')),
            ],
        ),
    ]
