# Generated by Django 3.2.16 on 2022-12-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekUserTopic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekusertopic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weekusertopic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='weekusertopic',
            name='weeks',
            field=models.IntegerField(null=True),
        ),
    ]
