# Generated by Django 3.2.16 on 2022-12-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weekUserTopic', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('week_user_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekUserTopic.weekusertopic')),
            ],
        ),
    ]
