# Generated by Django 3.2.16 on 2022-12-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_news1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_news1', to='userNews.usernews')),
                ('user_news2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_news2', to='userNews.usernews')),
                ('user_news3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_news3', to='userNews.usernews')),
            ],
        ),
    ]
